using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace SleepHunter.Forms
{
    public partial class frmMacro : Form
    {
        private IContainer components = null;
        private StatusStrip stbMain;
        internal ToolStripStatusLabel lblStatus;
        private ToolStripDropDownButton mnuDebug;
        private ToolStripMenuItem mnuLogic;
        private SplitContainer splMacroData;
        private SplitContainer splHeader;
        private GroupBox grpProcess;
        internal Label lblCharName;
        internal Label lblWindowHandle;
        internal Label lblProcessID;
        internal Label lblProcessName;
        private GroupBox grpMacro;
        private FlowLayoutPanel floMacro;
        private CheckBox chkHotkey;
        private TextBox txtHotkey;
        internal Label lblName;
        internal TextBox txtName;
        private Label lblVersion;
        internal ListView lvwMacro;
        private ColumnHeader colLine;
        private ColumnHeader colCommand;
        private ToolStrip tlbMacro;
        private ToolStripButton btnEdit;
        private ToolStripButton btnDelete;
        private ToolStripButton btnCut;
        private ToolStripButton btnCopy;
        private ToolStripButton btnPaste;
        private ToolStripButton btnMoveUp;
        private ToolStripButton btnMoveDown;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripButton btnPlay;
        private ToolStripButton btnPause;
        private ToolStripButton btnStop;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripDropDownButton btnQuickProc;
        internal ImageList ilsStatusIcons;
        private System.Windows.Forms.Timer tmrProcess;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(frmMacro));
            this.stbMain = new StatusStrip();
            this.lblStatus = new ToolStripStatusLabel();
            this.mnuDebug = new ToolStripDropDownButton();
            this.mnuLogic = new ToolStripMenuItem();
            this.splMacroData = new SplitContainer();
            this.splHeader = new SplitContainer();
            this.grpProcess = new GroupBox();
            this.lblCharName = new Label();
            this.lblWindowHandle = new Label();
            this.lblProcessID = new Label();
            this.lblProcessName = new Label();
            this.grpMacro = new GroupBox();
            this.floMacro = new FlowLayoutPanel();
            this.chkHotkey = new CheckBox();
            this.txtHotkey = new TextBox();
            this.lblName = new Label();
            this.txtName = new TextBox();
            this.lblVersion = new Label();
            this.lvwMacro = new ListView();
            this.colLine = new ColumnHeader();
            this.colCommand = new ColumnHeader();
            this.tlbMacro = new ToolStrip();
            this.btnEdit = new ToolStripButton();
            this.btnDelete = new ToolStripButton();
            this.btnCut = new ToolStripButton();
            this.btnCopy = new ToolStripButton();
            this.btnPaste = new ToolStripButton();
            this.btnMoveUp = new ToolStripButton();
            this.btnMoveDown = new ToolStripButton();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.btnPlay = new ToolStripButton();
            this.btnPause = new ToolStripButton();
            this.btnStop = new ToolStripButton();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.btnQuickProc = new ToolStripDropDownButton();
            this.ilsStatusIcons = new ImageList(this.components);
            this.tmrProcess = new System.Windows.Forms.Timer(this.components);
            this.stbMain.SuspendLayout();
            this.splMacroData.Panel1.SuspendLayout();
            this.splMacroData.Panel2.SuspendLayout();
            this.splMacroData.SuspendLayout();
            this.splHeader.Panel1.SuspendLayout();
            this.splHeader.Panel2.SuspendLayout();
            this.splHeader.SuspendLayout();
            this.grpProcess.SuspendLayout();
            this.grpMacro.SuspendLayout();
            this.floMacro.SuspendLayout();
            this.tlbMacro.SuspendLayout();
            this.SuspendLayout();
            this.stbMain.Items.AddRange(new ToolStripItem[2]
            {
                (ToolStripItem)this.lblStatus,
                (ToolStripItem)this.mnuDebug
            });
            this.stbMain.LayoutStyle = ToolStripLayoutStyle.Table;
            this.stbMain.Location = new Point(0, 326);
            this.stbMain.Name = "stbMain";
            this.stbMain.Size = new Size(452, 27);
            this.stbMain.TabIndex = 1;
            this.stbMain.Text = "statusStrip1";
            this.lblStatus.Image = (Image)resources.GetObject("lblStatus.Image");
            this.lblStatus.ImageAlign = ContentAlignment.MiddleLeft;
            this.lblStatus.ImageScaling = ToolStripItemImageScaling.None;
            this.lblStatus.MergeAction = MergeAction.Replace;
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Spring = true;
            this.lblStatus.Text = "Macro is not running.";
            this.lblStatus.TextAlign = ContentAlignment.MiddleLeft;
            this.mnuDebug.DropDownItems.AddRange(new ToolStripItem[1]
            {
                (ToolStripItem)this.mnuLogic
            });
            this.mnuDebug.Image = (Image)resources.GetObject("mnuDebug.Image");
            this.mnuDebug.ImageTransparentColor = Color.Magenta;
            this.mnuDebug.MergeAction = MergeAction.Replace;
            this.mnuDebug.Name = "mnuDebug";
            this.mnuDebug.Text = " Debug";
            this.mnuLogic.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.mnuLogic.MergeAction = MergeAction.Replace;
            this.mnuLogic.Name = "mnuLogic";
            this.mnuLogic.Text = "Generate Logic Skeleton";
            this.mnuLogic.Click += new EventHandler(this.mnuLogic_Click);
            this.splMacroData.Dock = DockStyle.Fill;
            this.splMacroData.FixedPanel = FixedPanel.Panel1;
            this.splMacroData.Location = new Point(0, 0);
            this.splMacroData.Name = "splMacroData";
            this.splMacroData.Orientation = Orientation.Horizontal;
            this.splMacroData.Panel1.Controls.Add((Control)this.splHeader);
            this.splMacroData.Panel1.Padding = new Padding(4);
            this.splMacroData.Panel2.Controls.Add((Control)this.lvwMacro);
            this.splMacroData.Panel2.Controls.Add((Control)this.tlbMacro);
            this.splMacroData.Panel2.Margin = new Padding(4);
            this.splMacroData.Panel2.Padding = new Padding(5, 1, 4, 4);
            this.splMacroData.Panel2.Paint += new PaintEventHandler(this.splMacroData_Panel2_Paint);
            this.splMacroData.Size = new Size(452, 326);
            this.splMacroData.SplitterDistance = 140;
            this.splMacroData.TabIndex = 2;
            this.splMacroData.Text = "splitContainer1";
            this.splHeader.Dock = DockStyle.Fill;
            this.splHeader.FixedPanel = FixedPanel.Panel1;
            this.splHeader.Location = new Point(4, 4);
            this.splHeader.Name = "splHeader";
            this.splHeader.Panel1.AllowDrop = true;
            this.splHeader.Panel1.Controls.Add((Control)this.grpProcess);
            this.splHeader.Panel1.Padding = new Padding(0, 0, 1, 0);
            this.splHeader.Panel1.DragDrop += new DragEventHandler(this.splHeader_Panel1_DragDrop);
            this.splHeader.Panel1.DragEnter += new DragEventHandler(this.splHeader_Panel1_DragEnter);
            this.splHeader.Panel2.Controls.Add((Control)this.grpMacro);
            this.splHeader.Panel2.Padding = new Padding(1, 0, 0, 0);
            this.splHeader.Size = new Size(444, 132);
            this.splHeader.SplitterDistance = 211;
            this.splHeader.TabIndex = 0;
            this.splHeader.Text = "splitContainer1";
            this.grpProcess.Controls.Add((Control)this.lblCharName);
            this.grpProcess.Controls.Add((Control)this.lblWindowHandle);
            this.grpProcess.Controls.Add((Control)this.lblProcessID);
            this.grpProcess.Controls.Add((Control)this.lblProcessName);
            this.grpProcess.Dock = DockStyle.Fill;
            this.grpProcess.ForeColor = SystemColors.ActiveCaption;
            this.grpProcess.Location = new Point(0, 0);
            this.grpProcess.Name = "grpProcess";
            this.grpProcess.Size = new Size(210, 132);
            this.grpProcess.TabIndex = 0;
            this.grpProcess.TabStop = false;
            this.grpProcess.Text = "Process Details";
            this.lblCharName.AutoEllipsis = true;
            this.lblCharName.AutoSize = true;
            this.lblCharName.Enabled = false;
            this.lblCharName.ForeColor = SystemColors.ControlText;
            this.lblCharName.Location = new Point(8, 56);
            this.lblCharName.Name = "lblCharName";
            this.lblCharName.Size = new Size(85, 13);
            this.lblCharName.TabIndex = 3;
            this.lblCharName.Text = "Character Name:";
            this.lblWindowHandle.AutoEllipsis = true;
            this.lblWindowHandle.AutoSize = true;
            this.lblWindowHandle.Enabled = false;
            this.lblWindowHandle.ForeColor = SystemColors.ControlText;
            this.lblWindowHandle.Location = new Point(8, 43);
            this.lblWindowHandle.Name = "lblWindowHandle";
            this.lblWindowHandle.Size = new Size(81, 13);
            this.lblWindowHandle.TabIndex = 2;
            this.lblWindowHandle.Text = "Window Handle:";
            this.lblProcessID.AutoEllipsis = true;
            this.lblProcessID.AutoSize = true;
            this.lblProcessID.Enabled = false;
            this.lblProcessID.ForeColor = SystemColors.ControlText;
            this.lblProcessID.Location = new Point(8, 30);
            this.lblProcessID.Name = "lblProcessID";
            this.lblProcessID.Size = new Size(58, 13);
            this.lblProcessID.TabIndex = 1;
            this.lblProcessID.Text = "Process ID:";
            this.lblProcessName.AutoEllipsis = true;
            this.lblProcessName.AutoSize = true;
            this.lblProcessName.Enabled = false;
            this.lblProcessName.ForeColor = SystemColors.ControlText;
            this.lblProcessName.Location = new Point(8, 17);
            this.lblProcessName.Name = "lblProcessName";
            this.lblProcessName.Size = new Size(74, 13);
            this.lblProcessName.TabIndex = 0;
            this.lblProcessName.Text = "Process Name:";
            this.grpMacro.Controls.Add((Control)this.floMacro);
            this.grpMacro.Dock = DockStyle.Fill;
            this.grpMacro.ForeColor = SystemColors.ActiveCaption;
            this.grpMacro.Location = new Point(1, 0);
            this.grpMacro.Name = "grpMacro";
            this.grpMacro.Size = new Size(228, 132);
            this.grpMacro.TabIndex = 0;
            this.grpMacro.TabStop = false;
            this.grpMacro.Text = "Macro Details";
            this.floMacro.Controls.Add((Control)this.chkHotkey);
            this.floMacro.Controls.Add((Control)this.txtHotkey);
            this.floMacro.Controls.Add((Control)this.lblName);
            this.floMacro.Controls.Add((Control)this.txtName);
            this.floMacro.Controls.Add((Control)this.lblVersion);
            this.floMacro.Dock = DockStyle.Fill;
            this.floMacro.FlowDirection = FlowDirection.TopDown;
            this.floMacro.Location = new Point(3, 17);
            this.floMacro.Margin = new Padding(3, 5, 3, 5);
            this.floMacro.Name = "floMacro";
            this.floMacro.Padding = new Padding(2);
            this.floMacro.Size = new Size(222, 112);
            this.floMacro.TabIndex = 0;
            this.chkHotkey.AutoSize = true;
            this.chkHotkey.Checked = true;
            this.chkHotkey.CheckState = CheckState.Checked;
            this.chkHotkey.FlatStyle = FlatStyle.System;
            this.chkHotkey.ForeColor = SystemColors.ControlText;
            this.chkHotkey.Location = new Point(5, 5);
            this.chkHotkey.Name = "chkHotkey";
            this.chkHotkey.Size = new Size(98, 18);
            this.chkHotkey.TabIndex = 5;
            this.chkHotkey.Text = "Macro Hotkey:";
            this.chkHotkey.CheckedChanged += new EventHandler(this.chkHotkey_CheckedChanged);
            this.txtHotkey.Dock = DockStyle.Fill;
            this.txtHotkey.Location = new Point(5, 29);
            this.txtHotkey.Name = "txtHotkey";
            this.txtHotkey.ReadOnly = true;
            this.txtHotkey.Size = new Size(212, 21);
            this.txtHotkey.TabIndex = 4;
            this.txtHotkey.Text = "Press Key Combination";
            this.txtHotkey.KeyDown += new KeyEventHandler(this.txtHotkey_KeyDown);
            this.lblName.AutoSize = true;
            this.lblName.ForeColor = SystemColors.ControlText;
            this.lblName.Location = new Point(5, 53);
            this.lblName.Name = "lblName";
            this.lblName.Size = new Size(66, 13);
            this.lblName.TabIndex = 0;
            this.lblName.Text = "Macro Name:";
            this.txtName.Dock = DockStyle.Fill;
            this.txtName.Location = new Point(5, 69);
            this.txtName.Name = "txtName";
            this.txtName.Size = new Size(212, 21);
            this.txtName.TabIndex = 1;
            this.txtName.TextChanged += new EventHandler(this.txtName_TextChanged);
            this.lblVersion.AutoSize = true;
            this.lblVersion.Enabled = false;
            this.lblVersion.ForeColor = SystemColors.ControlText;
            this.lblVersion.Location = new Point(5, 93);
            this.lblVersion.Name = "lblVersion";
            this.lblVersion.Size = new Size(61, 13);
            this.lblVersion.TabIndex = 2;
            this.lblVersion.Text = "File Version:";
            this.lblVersion.Visible = false;
            this.lvwMacro.AllowDrop = true;
            this.lvwMacro.BorderStyle = BorderStyle.None;
            this.lvwMacro.Columns.AddRange(new ColumnHeader[2]
            {
                this.colLine,
                this.colCommand
            });
            this.lvwMacro.Dock = DockStyle.Fill;
            this.lvwMacro.FullRowSelect = true;
            this.lvwMacro.HeaderStyle = ColumnHeaderStyle.Nonclickable;
            this.lvwMacro.HideSelection = false;
            this.lvwMacro.Location = new Point(5, 26);
            this.lvwMacro.Margin = new Padding(10);
            this.lvwMacro.Name = "lvwMacro";
            this.lvwMacro.Size = new Size(443, 152);
            this.lvwMacro.TabIndex = 0;
            this.lvwMacro.View = View.Details;
            this.lvwMacro.DragEnter += new DragEventHandler(this.lvwMacro_DragEnter);
            this.lvwMacro.DragDrop += new DragEventHandler(this.lvwMacro_DragDrop);
            this.lvwMacro.KeyDown += new KeyEventHandler(this.lvwMacro_KeyDown);
            this.colLine.Text = "Line #";
            this.colLine.Width = 45;
            this.colCommand.Text = "Command";
            this.colCommand.Width = 375;
            this.tlbMacro.Items.AddRange(new ToolStripItem[13]
            {
                (ToolStripItem)this.btnEdit,
                (ToolStripItem)this.btnDelete,
                (ToolStripItem)this.btnCut,
                (ToolStripItem)this.btnCopy,
                (ToolStripItem)this.btnPaste,
                (ToolStripItem)this.btnMoveUp,
                (ToolStripItem)this.btnMoveDown,
                (ToolStripItem)this.toolStripSeparator1,
                (ToolStripItem)this.btnPlay,
                (ToolStripItem)this.btnPause,
                (ToolStripItem)this.btnStop,
                (ToolStripItem)this.toolStripSeparator2,
                (ToolStripItem)this.btnQuickProc
            });
            this.tlbMacro.Location = new Point(5, 1);
            this.tlbMacro.Margin = new Padding(0, 10, 0, 10);
            this.tlbMacro.Name = "tlbMacro";
            this.tlbMacro.Size = new Size(443, 25);
            this.tlbMacro.TabIndex = 1;
            this.tlbMacro.Text = "toolStrip1";
            this.btnEdit.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnEdit.Image = (Image)resources.GetObject("btnEdit.Image");
            this.btnEdit.ImageScaling = ToolStripItemImageScaling.None;
            this.btnEdit.ImageTransparentColor = Color.Magenta;
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.Text = "toolStripButton1";
            this.btnEdit.ToolTipText = "Edit Command";
            this.btnEdit.Click += new EventHandler(this.btnEdit_Click);
            this.btnDelete.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnDelete.Image = (Image)resources.GetObject("btnDelete.Image");
            this.btnDelete.ImageScaling = ToolStripItemImageScaling.None;
            this.btnDelete.ImageTransparentColor = Color.Magenta;
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Text = "toolStripButton2";
            this.btnDelete.ToolTipText = "Delete Command(s)";
            this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
            this.btnCut.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnCut.Image = (Image)resources.GetObject("btnCut.Image");
            this.btnCut.ImageScaling = ToolStripItemImageScaling.None;
            this.btnCut.ImageTransparentColor = Color.Magenta;
            this.btnCut.Name = "btnCut";
            this.btnCut.Text = "toolStripButton3";
            this.btnCut.ToolTipText = "Cut Command(s)";
            this.btnCut.Click += new EventHandler(this.btnCut_Click);
            this.btnCopy.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnCopy.Image = (Image)resources.GetObject("btnCopy.Image");
            this.btnCopy.ImageScaling = ToolStripItemImageScaling.None;
            this.btnCopy.ImageTransparentColor = Color.Magenta;
            this.btnCopy.Name = "btnCopy";
            this.btnCopy.Text = "toolStripButton4";
            this.btnCopy.ToolTipText = "Copy Command(s)";
            this.btnCopy.Click += new EventHandler(this.btnCopy_Click);
            this.btnPaste.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnPaste.Image = (Image)resources.GetObject("btnPaste.Image");
            this.btnPaste.ImageScaling = ToolStripItemImageScaling.None;
            this.btnPaste.ImageTransparentColor = Color.Magenta;
            this.btnPaste.Name = "btnPaste";
            this.btnPaste.Text = "toolStripButton5";
            this.btnPaste.ToolTipText = "Paste Command(s)";
            this.btnPaste.Click += new EventHandler(this.btnPaste_Click);
            this.btnMoveUp.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnMoveUp.Image = (Image)resources.GetObject("btnMoveUp.Image");
            this.btnMoveUp.ImageScaling = ToolStripItemImageScaling.None;
            this.btnMoveUp.ImageTransparentColor = Color.Magenta;
            this.btnMoveUp.Name = "btnMoveUp";
            this.btnMoveUp.Text = "toolStripButton6";
            this.btnMoveUp.ToolTipText = "Move Up";
            this.btnMoveUp.Click += new EventHandler(this.btnMoveUp_Click);
            this.btnMoveDown.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnMoveDown.Image = (Image)resources.GetObject("btnMoveDown.Image");
            this.btnMoveDown.ImageTransparentColor = Color.Magenta;
            this.btnMoveDown.Name = "btnMoveDown";
            this.btnMoveDown.Text = "toolStripButton7";
            this.btnMoveDown.ToolTipText = "Move Down";
            this.btnMoveDown.Click += new EventHandler(this.btnMoveDown_Click);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.btnPlay.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnPlay.Image = (Image)resources.GetObject("btnPlay.Image");
            this.btnPlay.ImageScaling = ToolStripItemImageScaling.None;
            this.btnPlay.ImageTransparentColor = Color.Magenta;
            this.btnPlay.Name = "btnPlay";
            this.btnPlay.Text = "Play Macro";
            this.btnPlay.Click += new EventHandler(this.btnPlay_Click);
            this.btnPause.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnPause.Enabled = false;
            this.btnPause.Image = (Image)resources.GetObject("btnPause.Image");
            this.btnPause.ImageTransparentColor = Color.Magenta;
            this.btnPause.Name = "btnPause";
            this.btnPause.Text = "Pause Macro";
            this.btnPause.Click += new EventHandler(this.btnPause_Click);
            this.btnStop.DisplayStyle = ToolStripItemDisplayStyle.Image;
            this.btnStop.Enabled = false;
            this.btnStop.Image = (Image)resources.GetObject("btnStop.Image");
            this.btnStop.ImageScaling = ToolStripItemImageScaling.None;
            this.btnStop.ImageTransparentColor = Color.Magenta;
            this.btnStop.Name = "btnStop";
            this.btnStop.Text = "Stop Macro";
            this.btnStop.Click += new EventHandler(this.btnStop_Click);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.btnQuickProc.Image = (Image)resources.GetObject("btnQuickProc.Image");
            this.btnQuickProc.ImageScaling = ToolStripItemImageScaling.None;
            this.btnQuickProc.ImageTransparentColor = Color.Magenta;
            this.btnQuickProc.Name = "btnQuickProc";
            this.btnQuickProc.Text = " Quick Attach";
            this.btnQuickProc.ToolTipText = "Attach to Process";
            this.btnQuickProc.DropDownOpening += new EventHandler(this.btnQuickProc_DropDownOpening);
            this.ilsStatusIcons.ImageStream = (ImageListStreamer)resources.GetObject("ilsStatusIcons.ImageStream");
            this.ilsStatusIcons.Images.SetKeyName(0, "macro_play.ico");
            this.ilsStatusIcons.Images.SetKeyName(1, "macro_pause.ico");
            this.ilsStatusIcons.Images.SetKeyName(2, "macro_stop.ico");
            this.ilsStatusIcons.Images.SetKeyName(3, "services.ico");
            this.ilsStatusIcons.Images.SetKeyName(4, "Web_GlobalAppClass.ico");
            this.tmrProcess.Enabled = true;
            this.tmrProcess.Interval = 250;
            this.tmrProcess.Tick += new EventHandler(this.tmrProcess_Tick);
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(452, 353);
            this.Controls.Add((Control)this.splMacroData);
            this.Controls.Add((Control)this.stbMain);
            this.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.Name = "frmMacro";
            this.StartPosition = FormStartPosition.Manual;
            this.Text = "Macro Data";
            this.Load += new EventHandler(this.frmMacro_Load);
            this.Shown += new EventHandler(this.frmMacro_Shown);
            this.Activated += new EventHandler(this.frmMacro_Activated);
            this.FormClosing += new FormClosingEventHandler(this.frmMacro_FormClosing);
            this.stbMain.ResumeLayout(false);
            this.splMacroData.Panel1.ResumeLayout(false);
            this.splMacroData.Panel2.ResumeLayout(false);
            this.splMacroData.Panel2.PerformLayout();
            this.splMacroData.ResumeLayout(false);
            this.splHeader.Panel1.ResumeLayout(false);
            this.splHeader.Panel2.ResumeLayout(false);
            this.splHeader.ResumeLayout(false);
            this.grpProcess.ResumeLayout(false);
            this.grpProcess.PerformLayout();
            this.grpMacro.ResumeLayout(false);
            this.floMacro.ResumeLayout(false);
            this.floMacro.PerformLayout();
            this.tlbMacro.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
